# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Blog
    url: '#blogs'
    weight: 30
  - name: TidyTuesday
    url: '#tidytuesday'
    weight: 50
  - name: Notes
    url: '#notes'
    weight: 70
  - name: Training
    url: '#training'
    weight: 90
  - name: Publication
    url: '#publications'
    weight: 110
  - name: Contact
    url: '#contact'
    weight: 130
